/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as dashboardDashboardImport } from './routes/(dashboard)/_dashboard'
import { Route as authAuthImport } from './routes/(auth)/_auth'
import { Route as dashboardDashboardWorkspacesWorkspaceIdImport } from './routes/(dashboard)/_dashboard.workspaces.$workspaceId'
import { Route as dashboardstandaloneDashboardstandaloneImport } from './routes/(dashboard)/(standalone)/_dashboard_._standalone'
import { Route as authAuthSignUpSplatImport } from './routes/(auth)/_auth.sign-up.$'
import { Route as authAuthSignInSplatImport } from './routes/(auth)/_auth.sign-in.$'
import { Route as dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdImport } from './routes/(dashboard)/_dashboard.workspaces_.$workspaceId_.tasks_.$taskId'
import { Route as dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdImport } from './routes/(dashboard)/_dashboard.workspaces_.$workspaceId.projects.$projectId'
import { Route as dashboardstandaloneDashboardstandaloneWorkspacesCreateImport } from './routes/(dashboard)/(standalone)/_dashboard_._standalone.workspaces.create'
import { Route as dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsImport } from './routes/(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.settings'
import { Route as dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersImport } from './routes/(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.members'
import { Route as dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeImport } from './routes/(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.join.$joinCode'
import { Route as dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsImport } from './routes/(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.projects.$projectId.settings'

// Create Virtual Routes

const dashboardImport = createFileRoute('/(dashboard)')()
const authImport = createFileRoute('/(auth)')()
const dashboardstandaloneDashboardImport = createFileRoute(
  '/(dashboard)/(standalone)/_dashboard_',
)()

// Create/Update Routes

const dashboardRoute = dashboardImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardDashboardRoute = dashboardDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => dashboardRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)

const dashboardstandaloneDashboardRoute =
  dashboardstandaloneDashboardImport.update({
    id: '/(standalone)/_dashboard_',
    getParentRoute: () => dashboardRoute,
  } as any)

const dashboardDashboardWorkspacesWorkspaceIdRoute =
  dashboardDashboardWorkspacesWorkspaceIdImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

const dashboardstandaloneDashboardstandaloneRoute =
  dashboardstandaloneDashboardstandaloneImport.update({
    id: '/_standalone',
    getParentRoute: () => dashboardstandaloneDashboardRoute,
  } as any)

const authAuthSignUpSplatRoute = authAuthSignUpSplatImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => authAuthRoute,
} as any)

const authAuthSignInSplatRoute = authAuthSignInSplatImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => authAuthRoute,
} as any)

const dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute =
  dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdImport.update({
    id: '/workspaces_/$workspaceId_/tasks_/$taskId',
    path: '/workspaces/$workspaceId/tasks/$taskId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

const dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute =
  dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdImport.update({
    id: '/workspaces_/$workspaceId/projects/$projectId',
    path: '/workspaces/$workspaceId/projects/$projectId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

const dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute =
  dashboardstandaloneDashboardstandaloneWorkspacesCreateImport.update({
    id: '/workspaces/create',
    path: '/workspaces/create',
    getParentRoute: () => dashboardstandaloneDashboardstandaloneRoute,
  } as any)

const dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute =
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsImport.update(
    {
      id: '/workspaces/$workspaceId/settings',
      path: '/workspaces/$workspaceId/settings',
      getParentRoute: () => dashboardstandaloneDashboardstandaloneRoute,
    } as any,
  )

const dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute =
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersImport.update(
    {
      id: '/workspaces/$workspaceId/members',
      path: '/workspaces/$workspaceId/members',
      getParentRoute: () => dashboardstandaloneDashboardstandaloneRoute,
    } as any,
  )

const dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute =
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeImport.update(
    {
      id: '/workspaces/$workspaceId/join/$joinCode',
      path: '/workspaces/$workspaceId/join/$joinCode',
      getParentRoute: () => dashboardstandaloneDashboardstandaloneRoute,
    } as any,
  )

const dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute =
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsImport.update(
    {
      id: '/workspaces/$workspaceId/projects/$projectId/settings',
      path: '/workspaces/$workspaceId/projects/$projectId/settings',
      getParentRoute: () => dashboardstandaloneDashboardstandaloneRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof authRoute
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_dashboard': {
      id: '/(dashboard)/_dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardDashboardImport
      parentRoute: typeof dashboardRoute
    }
    '/(auth)/_auth/sign-in/$': {
      id: '/(auth)/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof authAuthSignInSplatImport
      parentRoute: typeof authAuthImport
    }
    '/(auth)/_auth/sign-up/$': {
      id: '/(auth)/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof authAuthSignUpSplatImport
      parentRoute: typeof authAuthImport
    }
    '/(dashboard)/(standalone)/_dashboard_': {
      id: '/(dashboard)/(standalone)/_dashboard_'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardstandaloneDashboardImport
      parentRoute: typeof dashboardImport
    }
    '/(dashboard)/(standalone)/_dashboard_/_standalone': {
      id: '/(dashboard)/(standalone)/_dashboard_/_standalone'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardstandaloneDashboardstandaloneImport
      parentRoute: typeof dashboardstandaloneDashboardRoute
    }
    '/(dashboard)/_dashboard/workspaces/$workspaceId': {
      id: '/(dashboard)/_dashboard/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof dashboardDashboardWorkspacesWorkspaceIdImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/create': {
      id: '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesCreateImport
      parentRoute: typeof dashboardstandaloneDashboardstandaloneImport
    }
    '/(dashboard)/_dashboard/workspaces_/$workspaceId/projects/$projectId': {
      id: '/(dashboard)/_dashboard/workspaces_/$workspaceId/projects/$projectId'
      path: '/workspaces/$workspaceId/projects/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/_dashboard/workspaces_/$workspaceId_/tasks_/$taskId': {
      id: '/(dashboard)/_dashboard/workspaces_/$workspaceId_/tasks_/$taskId'
      path: '/workspaces/$workspaceId/tasks/$taskId'
      fullPath: '/workspaces/$workspaceId/tasks/$taskId'
      preLoaderRoute: typeof dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/members': {
      id: '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/members'
      path: '/workspaces/$workspaceId/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersImport
      parentRoute: typeof dashboardstandaloneDashboardstandaloneImport
    }
    '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/settings': {
      id: '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/settings'
      path: '/workspaces/$workspaceId/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsImport
      parentRoute: typeof dashboardstandaloneDashboardstandaloneImport
    }
    '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/join/$joinCode': {
      id: '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/join/$joinCode'
      path: '/workspaces/$workspaceId/join/$joinCode'
      fullPath: '/workspaces/$workspaceId/join/$joinCode'
      preLoaderRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeImport
      parentRoute: typeof dashboardstandaloneDashboardstandaloneImport
    }
    '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/projects/$projectId/settings': {
      id: '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/projects/$projectId/settings'
      path: '/workspaces/$workspaceId/projects/$projectId/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/settings'
      preLoaderRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsImport
      parentRoute: typeof dashboardstandaloneDashboardstandaloneImport
    }
  }
}

// Create and export the route tree

interface authAuthRouteChildren {
  authAuthSignInSplatRoute: typeof authAuthSignInSplatRoute
  authAuthSignUpSplatRoute: typeof authAuthSignUpSplatRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthSignInSplatRoute: authAuthSignInSplatRoute,
  authAuthSignUpSplatRoute: authAuthSignUpSplatRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface dashboardDashboardRouteChildren {
  dashboardDashboardWorkspacesWorkspaceIdRoute: typeof dashboardDashboardWorkspacesWorkspaceIdRoute
  dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute: typeof dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute
  dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute: typeof dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardWorkspacesWorkspaceIdRoute:
    dashboardDashboardWorkspacesWorkspaceIdRoute,
  dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute:
    dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute,
  dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute:
    dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

interface dashboardstandaloneDashboardstandaloneRouteChildren {
  dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute
  dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute: typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
}

const dashboardstandaloneDashboardstandaloneRouteChildren: dashboardstandaloneDashboardstandaloneRouteChildren =
  {
    dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute:
      dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute,
    dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute:
      dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute,
    dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute:
      dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute,
    dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute:
      dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute,
    dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute:
      dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute,
  }

const dashboardstandaloneDashboardstandaloneRouteWithChildren =
  dashboardstandaloneDashboardstandaloneRoute._addFileChildren(
    dashboardstandaloneDashboardstandaloneRouteChildren,
  )

interface dashboardstandaloneDashboardRouteChildren {
  dashboardstandaloneDashboardstandaloneRoute: typeof dashboardstandaloneDashboardstandaloneRouteWithChildren
}

const dashboardstandaloneDashboardRouteChildren: dashboardstandaloneDashboardRouteChildren =
  {
    dashboardstandaloneDashboardstandaloneRoute:
      dashboardstandaloneDashboardstandaloneRouteWithChildren,
  }

const dashboardstandaloneDashboardRouteWithChildren =
  dashboardstandaloneDashboardRoute._addFileChildren(
    dashboardstandaloneDashboardRouteChildren,
  )

interface dashboardRouteChildren {
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
  dashboardstandaloneDashboardRoute: typeof dashboardstandaloneDashboardRouteWithChildren
}

const dashboardRouteChildren: dashboardRouteChildren = {
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
  dashboardstandaloneDashboardRoute:
    dashboardstandaloneDashboardRouteWithChildren,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardstandaloneDashboardstandaloneRouteWithChildren
  '/sign-in/$': typeof authAuthSignInSplatRoute
  '/sign-up/$': typeof authAuthSignUpSplatRoute
  '/workspaces/$workspaceId': typeof dashboardDashboardWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute
  '/workspaces/$workspaceId/tasks/$taskId': typeof dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute
  '/workspaces/$workspaceId/members': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute
  '/workspaces/$workspaceId/settings': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/join/$joinCode': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof dashboardstandaloneDashboardstandaloneRouteWithChildren
  '/sign-in/$': typeof authAuthSignInSplatRoute
  '/sign-up/$': typeof authAuthSignUpSplatRoute
  '/workspaces/$workspaceId': typeof dashboardDashboardWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute
  '/workspaces/$workspaceId/tasks/$taskId': typeof dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute
  '/workspaces/$workspaceId/members': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute
  '/workspaces/$workspaceId/settings': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/join/$joinCode': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(dashboard)': typeof dashboardRouteWithChildren
  '/(dashboard)/_dashboard': typeof dashboardDashboardRouteWithChildren
  '/(auth)/_auth/sign-in/$': typeof authAuthSignInSplatRoute
  '/(auth)/_auth/sign-up/$': typeof authAuthSignUpSplatRoute
  '/(dashboard)/(standalone)/_dashboard_': typeof dashboardstandaloneDashboardRouteWithChildren
  '/(dashboard)/(standalone)/_dashboard_/_standalone': typeof dashboardstandaloneDashboardstandaloneRouteWithChildren
  '/(dashboard)/_dashboard/workspaces/$workspaceId': typeof dashboardDashboardWorkspacesWorkspaceIdRoute
  '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/create': typeof dashboardstandaloneDashboardstandaloneWorkspacesCreateRoute
  '/(dashboard)/_dashboard/workspaces_/$workspaceId/projects/$projectId': typeof dashboardDashboardWorkspacesWorkspaceIdProjectsProjectIdRoute
  '/(dashboard)/_dashboard/workspaces_/$workspaceId_/tasks_/$taskId': typeof dashboardDashboardWorkspacesWorkspaceIdTasksTaskIdRoute
  '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/members': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdMembersRoute
  '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/settings': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdSettingsRoute
  '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/join/$joinCode': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdJoinJoinCodeRoute
  '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/projects/$projectId/settings': typeof dashboardstandaloneDashboardstandaloneWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/tasks/$taskId'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/join/$joinCode'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/projects/$projectId'
    | '/workspaces/$workspaceId/tasks/$taskId'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/join/$joinCode'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(dashboard)'
    | '/(dashboard)/_dashboard'
    | '/(auth)/_auth/sign-in/$'
    | '/(auth)/_auth/sign-up/$'
    | '/(dashboard)/(standalone)/_dashboard_'
    | '/(dashboard)/(standalone)/_dashboard_/_standalone'
    | '/(dashboard)/_dashboard/workspaces/$workspaceId'
    | '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/create'
    | '/(dashboard)/_dashboard/workspaces_/$workspaceId/projects/$projectId'
    | '/(dashboard)/_dashboard/workspaces_/$workspaceId_/tasks_/$taskId'
    | '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/members'
    | '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/settings'
    | '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/join/$joinCode'
    | '/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/projects/$projectId/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRoute: typeof authRouteWithChildren
  dashboardRoute: typeof dashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRoute: authRouteWithChildren,
  dashboardRoute: dashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/(dashboard)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth"
      ]
    },
    "/(auth)/_auth": {
      "filePath": "(auth)/_auth.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth/sign-in/$",
        "/(auth)/_auth/sign-up/$"
      ]
    },
    "/(dashboard)": {
      "filePath": "(dashboard)",
      "children": [
        "/(dashboard)/_dashboard",
        "/(dashboard)/(standalone)/_dashboard_"
      ]
    },
    "/(dashboard)/_dashboard": {
      "filePath": "(dashboard)/_dashboard.tsx",
      "parent": "/(dashboard)",
      "children": [
        "/(dashboard)/_dashboard/workspaces/$workspaceId",
        "/(dashboard)/_dashboard/workspaces_/$workspaceId/projects/$projectId",
        "/(dashboard)/_dashboard/workspaces_/$workspaceId_/tasks_/$taskId"
      ]
    },
    "/(auth)/_auth/sign-in/$": {
      "filePath": "(auth)/_auth.sign-in.$.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(auth)/_auth/sign-up/$": {
      "filePath": "(auth)/_auth.sign-up.$.tsx",
      "parent": "/(auth)/_auth"
    },
    "/(dashboard)/(standalone)/_dashboard_": {
      "filePath": "(dashboard)/(standalone)",
      "parent": "/(dashboard)",
      "children": [
        "/(dashboard)/(standalone)/_dashboard_/_standalone"
      ]
    },
    "/(dashboard)/(standalone)/_dashboard_/_standalone": {
      "filePath": "(dashboard)/(standalone)/_dashboard_._standalone.tsx",
      "parent": "/(dashboard)/(standalone)/_dashboard_",
      "children": [
        "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/create",
        "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/members",
        "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/settings",
        "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/join/$joinCode",
        "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/projects/$projectId/settings"
      ]
    },
    "/(dashboard)/_dashboard/workspaces/$workspaceId": {
      "filePath": "(dashboard)/_dashboard.workspaces.$workspaceId.tsx",
      "parent": "/(dashboard)/_dashboard"
    },
    "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/create": {
      "filePath": "(dashboard)/(standalone)/_dashboard_._standalone.workspaces.create.tsx",
      "parent": "/(dashboard)/(standalone)/_dashboard_/_standalone"
    },
    "/(dashboard)/_dashboard/workspaces_/$workspaceId/projects/$projectId": {
      "filePath": "(dashboard)/_dashboard.workspaces_.$workspaceId.projects.$projectId.tsx",
      "parent": "/(dashboard)/_dashboard"
    },
    "/(dashboard)/_dashboard/workspaces_/$workspaceId_/tasks_/$taskId": {
      "filePath": "(dashboard)/_dashboard.workspaces_.$workspaceId_.tasks_.$taskId.tsx",
      "parent": "/(dashboard)/_dashboard"
    },
    "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/members": {
      "filePath": "(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.members.tsx",
      "parent": "/(dashboard)/(standalone)/_dashboard_/_standalone"
    },
    "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/settings": {
      "filePath": "(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.settings.tsx",
      "parent": "/(dashboard)/(standalone)/_dashboard_/_standalone"
    },
    "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/join/$joinCode": {
      "filePath": "(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.join.$joinCode.tsx",
      "parent": "/(dashboard)/(standalone)/_dashboard_/_standalone"
    },
    "/(dashboard)/(standalone)/_dashboard_/_standalone/workspaces/$workspaceId/projects/$projectId/settings": {
      "filePath": "(dashboard)/(standalone)/_dashboard_._standalone.workspaces.$workspaceId.projects.$projectId.settings.tsx",
      "parent": "/(dashboard)/(standalone)/_dashboard_/_standalone"
    }
  }
}
ROUTE_MANIFEST_END */
